### PR TITLE
use jquerylib

### LINKED ISSUE #5: use jquerylib to get jQuery dependency
use [jquerylib](https://github.com/rstudio/jquerylib) to manage the jQuery dependency so that a version of jQuery does not have to be included inside of this package

### PR DESCRIPTION
**Pull request by cjyetman**
use jquerylib instead of including jQuery in this repo/pkg

closes #5

### CODE REVIEW

**Comment by cjyetman** [comment]
side note: @jdhoffa or @maurolepore I'd like to understand why the commit history from previous branches is following me around and how to get rid of it here for instance, while complying with the "don't change the shared git history" guideline

**Review by maurolepore — APPROVED** [review]
LGTM.

**Comment by maurolepore** [comment]
> why the commit history from previous branches is following me around and how to get rid of it here for instance

I usually get in that situation when I create a new branch not off `master` but off the head of an existing PR. I don't know how to fix this PR and instead I would close it and resubmit. The new one should have all relevant commits on top of `master` -- after you ensure that `master` is in sync with `origin/master`.

To move the relevant commits you may use create and checkout a new bransh off the syncronized `master`, then `git cherry-pick sha1 sha1 sha3` or move all commits at once with `git rebase --onto master sha1 sha3` -- but please check the docs because I use `git rebase --onto` infrequently. Jackson may have it fresh in his mind.

**Comment by jdhoffa** [comment]
Indeed, so you wouldn't/ shouldn't do the rebase on a shared branch (ie. this one). 
The process would be: 
* Close this PR
* Checkout a new branch (from the branch `use-jquerylib-#5`), called `use-jquerylib-clean#5` or something like that
* This new branch will now only be local, so you can rebase
* The `rebase --onto` is handy if you happen to know which branch gave you these leftover commits (I gave a pretty in depth explanation of it in #coding on slack, can tag you if you're interested)
* Otherwise, I would use Mauro's cherry pick option

**Comment by cjyetman** [comment]
closing this in favor of #9 

fyi... using RStudio's git pane, this is how I ended up doing this...
1. switched/checked-out to this branch use-jquerylib-#5
2. used the new branch button to create a new branch
3. set the new branch name to use-jquerylib-clean#5 and left the "Sync branch with remote" option checked

and that was it... came to GitHub and it offered to start a new PR based on this new branch that had been created... and the new branch/PR has only the one commit I wanted in it

🤷🏻

**Pull request closed without merging**
