### PR TITLE
add the most basic tests

### PR DESCRIPTION
**Pull request by cjyetman**
Add the most basic tests for the five current interactive plots. Also required adding audit_file and results_map to the test.rda and a setup.R to give the tests acceptable performance

~~somewhat depends on #8 because one of the tests will fail until that has been merged~~

### CODE REVIEW

**Comment by cjyetman** [comment]
fyi... these tests (or at least one of them) will fail until #8 is merged

**Review by maurolepore — APPROVED** [review]
Thanks! It's so nice to be able to learn so quickly what the package actually does.

BTW, your comment suggests the tests are slow? Is there room to make the data smaller? Particularly for this test cases that are only concerned with the class of output but not what the output is?

**Comment by maurolepore** [comment]
> fyi... these tests (or at least one of them) will fail until #8 is merged

Interesting. I see all checks pass suggesting that either the comment is outdated or the potentially failing test actually passes.

**Comment by cjyetman** [comment]
> I see all checks pass suggesting that either the comment is outdated or the potentially failing test actually passes.

yes, outdated in the sense that #8 has been merged

**Comment by cjyetman** [comment]
> BTW, your comment suggests the tests are slow? Is there room to make the data smaller? Particularly for this test cases that are only concerned with the class of output but not what the output is?

Yes, there is probably room to further shrink the test data while still retaining the characteristics and variation needed to demonstrate a variety of uses cases and edge cases. That, in my opinion, is a rather large task on its own. Maybe make an issue about it so it stays on the radar?

**Pull request merged**
